### PR TITLE
Use DiffEqProblemLibrary and add tests

### PR DESCRIPTION
**Pull request by devmotion**
Hi!

Already shortly after https://github.com/JuliaDiffEq/DiffEqProblemLibrary.jl/pull/9 was merged I wanted to open this PR in order to use `DiffEqProblemLibrary.jl` in the tests. However, by adding some additional tests I discovered that the unconstrained algorithm computes different solutions for in-place and not in-place functions. I tried to fix this problem, but without success yet. I'll open an issue regarding this problem, the failing tests are commented out in this PR.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Instead of commenting them out, can you add `@test_broken`? Need to check around for a place where the values alias. Thanks for catching it.

**Comment by devmotion** [comment]
Tests work locally, but will fail on Travis etc because there is no release of `DiffEqProblemLibrary.jl` with DDE problems yet.

**Comment by ChrisRackauckas** [comment]
Got it. I'll just tag that right now.

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/10216

**Pull request merged**
