### PR TITLE
Avoid duplicate end points with saveat

### PR DESCRIPTION
**Pull request by devmotion**
Fix https://github.com/JuliaDiffEq/DelayDiffEq.jl/issues/93.

### CODE REVIEW

**Comment by devmotion** [comment]
Any idea for why Vern6 and Vern9 tests fail on Julia stable (in my branch) and on Julia nightlies (in your branch) but succeed on nightlies and on stable, respectively? Seems strange....

**Comment by devmotion** [comment]
The same error occurred before: https://travis-ci.org/JuliaDiffEq/DelayDiffEq.jl/jobs/475655707

**Comment by ChrisRackauckas** [comment]
It might be a small floating point difference that causes a rejected step to change to accepted in the different forms.

**Comment by ChrisRackauckas** [comment]
Since it's working on the nightly I'll merge it, but it is quite curious.

**Comment by devmotion** [comment]
I'm especially surprised about the fact that it both fails and succeeds on the nightly and the stable version from time to time - maybe it just depends on which computer/architecture is used for the Travis tests?

**Pull request merged**
