### PR TITLE
Keep track of broken tests on 32bit systems

### PR DESCRIPTION
**Pull request by devmotion**

### CODE REVIEW

**Comment by devmotion** [comment]
I'm running separate (hopefully faster) Appveyor tests on my fork: https://ci.appveyor.com/project/devmotion/delaydiffeq-jl-p4v3l

**Comment by ChrisRackauckas** [comment]
Feel free to change the main AppVeyor of DelayDiffEq to your AppVeyor. I think that will take a load off.

**Comment by devmotion** [comment]
OK, I added it to my account, so hopefully the Appveyor tests run a bit faster from now on. I'll update the Appveyor badge if it works.

**Comment by devmotion** [comment]
Win32 tests (for Julia 1.1) passed in my AppVeyor.

**Pull request merged**
