### PR TITLE
Test Failure Fixes

### PR DESCRIPTION
**Pull request by kanav99**
Something weird happened between 21 March - 8 April in OrdinaryDiffEq due to which errors have increased but steps have decreased. DelayDiffEq was also hit by this. And its not algorithm specific, but for all the algorithms.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/5263f5be5248cfff464ec80037c987df765fc493 made cases where `du = 0` have a more stable inital `dt`, but that would've changed the initial `dt` as well.

**Comment by kanav99** [comment]
Yes this is it. This is the culprit. I tried running tests before and after the commit and it passes before that!

**Comment by kanav99** [comment]
Commenting out those two lines made all the tests pass. I will understand the AD problem and make a patch there. We might need to tighten the tolerances in OrdinaryDiffEq tests too.

**Comment by ChrisRackauckas** [comment]
The OrdinaryDiffEq.jl change should be harmless here.

**Comment by kanav99** [comment]
On turning Off the AD fix, the tests pass, what should I do? Increase the estimates or make a fix in OrdinaryDIffEq? Or maybe a special implementation of `ode_determine_initdt`?

**Comment by ChrisRackauckas** [comment]
Increase the estimates. It means they were too tight: they shouldn't fail due to a change in init dt.

**Comment by kanav99** [comment]
I have marked a test broken because this PR was getting long and master is broken right now. I will handle the broken test in a seperate PR and merge this once this passes tests.

**Comment by ChrisRackauckas** [comment]
Sounds good. Yeah seems like it's just a bunch of too strict regression tests

**Pull request merged**
