### PR TITLE
Fix constant extrapolation

### PR DESCRIPTION
**Pull request by devmotion**
Constant extrapolation at the initial time point currently does not work, as shown in https://github.com/JuliaDiffEq/DelayDiffEq.jl/issues/40.

We should also add tests for `HistoryFunction` which should have catched these errors.

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
How about adding that test problem?

**Comment by devmotion** [comment]
I added the test problem, but also some other more basic tests which should cover most functionality of `HistoryFunction`. These tests catched two additional bugs.

**Comment by ChrisRackauckas** [comment]
For reference what were those bugs?

**Comment by devmotion** [comment]
Two bugs in the implementation of `constant_extrapolant!`: a typo in line https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/src/interpolants.jl#L47 (should be `val` instead of `out`) and a missing `[idxs]` in line https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/src/interpolants.jl#L61.

**Pull request merged**
