### PR TITLE
Help the compiler

### PR DESCRIPTION
**Pull request by devmotion**
The compiler seems to have a hard time figuring out the return type of function calls such as
```julia
init(DDEProblemLibrary.prob_dde_constant_1delay_ip, MethodOfSteps(Tsit5()))
```
even though we try to specify the type parameters of the DDEIntegrator. On the master branch, e.g., I get
```julia
julia> @code_warntype init(DDEProblemLibrary.prob_dde_constant_1delay_ip, MethodOfSteps(Tsit5()));
....
│    %51 = invoke %47(%22::DDEProblem{Array{Float64,1},Tuple{Float64,Float64},Array{Int64,1},Tuple{},true,DataType,DDEFunction{true,typeof(DiffEqProblemLibrary.DDEProblemLibrary.f_dde_constant_1delay_ip!),LinearAlgebra.UniformScaling{Bool},typeof(DiffEqProblemLibrary.DDEProblemLibrary.fanalytic_dde_constant_1delay),Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(DiffEqProblemLibrary.DDEProblemLibrary.h_dde_constant_ip),Nothing}, %1::MethodOfSteps{Tsit5,Nothing,Nothing,Nothing,false}, %48::Array{Array{Float64,1},1}, %49::Array{Float64,1}, %50::Array{Any,1})::DelayDiffEq.DDEIntegrator{Tsit5,true,_1,_2,_3,_4,_5,_6,_7,_8,_9,Array{Array{Float64,1},1},_10,_11,_12,_13,_14,_15,Float64,Int64,Array{Float64,1},_16,Nothing} where _16 where _15 where _14 where _13 where _12 where _11 where _10 where _9 where _8 where _7 where _6 where _5 where _4 where _3 where _2 where _1
└───       goto #28
28 ─       return %51
```
By just changing `p` to `prob.p` in https://github.com/JuliaDiffEq/DelayDiffEq.jl/blob/master/src/solve.jl#L258, the compiler is able to figure out that type parameter correctly. So I suspect that type inference breaks down at some point. I still don't understand why this becomes only apparent after having simplified our nested type structures a bit.

In this PR I tried reduce the number of non-inferred type parameters as much as possible and at the same time I replaced the full ODE integrator with a very reduced integrator that only contains a very reduced set of objects (and hence types) compared with a full ODE integrator. Additionally I started breaking the function into smaller pieces, hoping that this would help the compiler as well.

So far, I've managed to get the number of non-inferred types down to 5:
```julia
│    %51 = invoke %47(%22::DDEProblem{Array{Float64,1},Tuple{Float64,Float64},Array{Int64,1},Tuple{},true,DataType,DDEFunction{true,typeof(DiffEqProblemLibrary.DDEProblemLibrary.f_dde_constant_1delay_ip!),LinearAlgebra.UniformScaling{Bool},typeof(DiffEqProblemLibrary.DDEProblemLibrary.fanalytic_dde_constant_1delay),Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},typeof(DiffEqProblemLibrary.DDEProblemLibrary.h_dde_constant_ip),Nothing}, %1::MethodOfSteps{Tsit5,Nothing,Nothing,Nothing,false}, %48::Array{Array{Float64,1},1}, %49::Array{Float64,1}, %50::Array{Any,1})::DelayDiffEq.DDEIntegrator{Tsit5,true,Array{Float64,1},Float64,DataType,Float64,Float64,Float64,Array{Float64,1},Float64,Float64,Array{Array{Float64,1},1},_1,_2,_3,_4,typeof(DiffEqBase.ODE_DEFAULT_NORM),_5,Float64,Int64,Array{Float64,1},Float64,Nothing} where _5 where _4 where _3 where _2 where _1
└───       goto #28
28 ─       return %51
```

Unfortunately this does not fix the long compilation times completely, but at least on Travis after some initial delay this version is a lot faster and produces much less allocations than even the old version roughly half a month ago (https://travis-ci.org/JuliaDiffEq/DelayDiffEq.jl/jobs/554737616 vs https://travis-ci.org/JuliaDiffEq/DelayDiffEq.jl/jobs/560087842). I don't know why but it seems compiling on Windows 32bit still takes forever: https://ci.appveyor.com/project/devmotion/delaydiffeq-jl-ungfr/build/job/95dsd9ubj4sa1r5n

### CODE REVIEW

**Comment by ChrisRackauckas** [comment]
Nice! @kanav99 you wanted to look into doing something similar with OrdinaryDiffEq? It sounds like that would be promising, and that would help DelayDiffEq too.

**Comment by devmotion** [comment]
With Julia 1.2 rc2 I get
```julia
│   %4 = Core._apply(DiffEqBase.:(#init#380), %3, args)::DelayDiffEq.DDEIntegrator{Tsit5,true,Array{Float64,1},Float64,DataType,Float64,Float64,Float64,Array{Float64,1},Float64,Float64,Array{Array{Float64,1},1},_A,_B,OrdinaryDiffEq.Tsit5Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}},DelayDiffEq.HistoryFunction{typeof(DiffEqProblemLibrary.DDEProblemLibrary.h_dde_constant_ip),DelayDiffEq.HistoryODEIntegrator{Tsit5,true,Array{Float64,1},Float64,Float64,Array{Array{Float64,1},1},ODESolution{Float64,2,Array{Array{Float64,1},1},Nothing,Nothing,Array{Float64,1},Array{Array{Array{Float64,1},1},1},ODEProblem{Array{Float64,1},Tuple{Float64,Float64},true,DataType,ODEFunction{true,getfield(DelayDiffEq, Symbol("##38#40")){DDEFunction{true,typeof(DiffEqProblemLibrary.DDEProblemLibrary.f_dde_constant_1delay_ip!),LinearAlgebra.UniformScaling{Bool},typeof(DiffEqProblemLibrary.DDEProblemLibrary.fanalytic_dde_constant_1delay),Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing}},LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Nothing,DiffEqBase.StandardODEProblem},Tsit5,OrdinaryDiffEq.InterpolationData{ODEFunction{true,getfield(DelayDiffEq, Symbol("##38#40")){DDEFunction{true,typeof(DiffEqProblemLibrary.DDEProblemLibrary.f_dde_constant_1delay_ip!),LinearAlgebra.UniformScaling{Bool},typeof(DiffEqProblemLibrary.DDEProblemLibrary.fanalytic_dde_constant_1delay),Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing}},LinearAlgebra.UniformScaling{Bool},Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing,Nothing},Array{Array{Float64,1},1},Array{Float64,1},Array{Array{Array{Float64,1},1},1},OrdinaryDiffEq.Tsit5Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}},DiffEqBase.DEStats},OrdinaryDiffEq.Tsit5Cache{Array{Float64,1},Array{Float64,1},Array{Float64,1},OrdinaryDiffEq.Tsit5ConstantCache{Float64,Float64}}}},typeof(DiffEqBase.ODE_DEFAULT_NORM),_C,Float64,Int64,Array{Float64,1},Float64,Nothing} where _C where _B where _A
```
i.e. only 3 type parameters (the type of the solution, the ODE Function that wraps the history function, and the DEOptions) are not inferred.

**Comment by devmotion** [comment]
I forgot to mention that this PR also fixes https://github.com/JuliaDiffEq/DelayDiffEq.jl/issues/127.

I'm still puzzled by the long compilation on Win32, but at least it runs successfully (and very fast) after waiting for 2200 sec :laughing:

**Comment by ChrisRackauckas** [comment]
Is this still necessary?

**Comment by devmotion** [comment]
No, I just checked, and
```julia
init(DDEProblemLibrary.prob_dde_constant_1delay_ip, MethodOfSteps(Tsit5()))
```
is correctly inferred with Julia 1.1.1 and Julia 1.3 on master.

**Pull request closed without merging**
