### PR TITLE
Avoid duplicate Travis CI tests in PRs

### PR DESCRIPTION
**Pull request by devmotion**
I'm not completely sure if it works, but maybe this change lets us get rid of duplicate tests in PRs and reduce the load on Travis.

### CODE REVIEW

**Comment by devmotion** [comment]
I shouldn't rerun the tests so often :smile: It seems the latest changes of the handling of the DtMin return code in https://github.com/JuliaDiffEq/DiffEqBase.jl/blob/master/src/integrator_interface.jl are responsible for the test failures.

**Comment by ChrisRackauckas** [comment]
ugh, how could that be? It should have only less of a chance of exiting with that condition.

**Comment by devmotion** [comment]
Sure, but the tests expect the solver to exit with that condition. After the latest changes the maximum number of iterations are reached instead. So should the tests be changed? Or is there an issue that has to be fixed?

**Comment by ChrisRackauckas** [comment]
I can take a look. The issue is that you won't hit that dt issue unless you really should. Why it's not the case here is odd...

**Comment by devmotion** [comment]
Have you had time to take a look if there's a regression or if we should just change the tests?

**Comment by ChrisRackauckas** [comment]
Awesome.

**Pull request merged**
